logging:
  config: classpath:log4j2.xml
server:
  port: 8080
  servlet:
    context-path: /gd
spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/knowledge_new?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 5
      minimum-idle: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  thymeleaf:
    mode: HTML 5
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    encoding: utf-8
    suffix: .html
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dong.graduate.model
  global-config:
    db-config:
      field-strategy: ignored
      id-type: auto
      db-type: mysql
    banner: false





